from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from repoboost.recommendations import Recommendation, generate_recommendations
from repoboost.scanner import CheckResult, ScanReport, scan_project


@dataclass
class MarkdownReport:
    path: str
    content: str

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "content": self.content,
        }


def generate_markdown_report(
    path: str | Path,
    config_path: str | Path | None = None,
    include_passed: bool = True,
    recommendation_limit: int = 8,
) -> MarkdownReport:
    root = Path(path).resolve()
    scan_report = scan_project(root, config_path=config_path)
    recommendations = generate_recommendations(
        root,
        limit=recommendation_limit,
        config_path=config_path,
    )

    content = _build_markdown_report(
        scan_report=scan_report,
        recommendations=recommendations,
        include_passed=include_passed,
    )

    return MarkdownReport(
        path=str(root),
        content=content,
    )


def _build_markdown_report(
    scan_report: ScanReport,
    recommendations: list[Recommendation],
    include_passed: bool,
) -> str:
    lines: list[str] = []

    lines.append("# RepoBoost Report")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Path:** `{scan_report.path}`")
    lines.append(f"- **Score:** `{scan_report.score}/{scan_report.max_score}`")
    lines.append(f"- **Percentage:** `{scan_report.percentage}%`")
    lines.append(f"- **Grade:** `{scan_report.grade}`")
    lines.append(f"- **Profile:** `{scan_report.profile}`")

    if scan_report.config_path:
        lines.append(f"- **Config:** `{scan_report.config_path}`")

    lines.append("")
    lines.append("## Audit Results")
    lines.append("")
    lines.append("| Status | Check | Score | Message | Suggestion |")
    lines.append("| --- | --- | ---: | --- | --- |")

    checks = scan_report.checks if include_passed else [
        check for check in scan_report.checks if not check.passed
    ]

    if checks:
        for check in checks:
            lines.append(_format_check_row(check))
    else:
        lines.append("| ✅ PASS | No missing checks | 0/0 | No missing checks found. | No action needed. |")

    lines.append("")
    lines.append("## Recommendations")
    lines.append("")

    if recommendations:
        lines.append("| Priority | Category | Recommendation | Action |")
        lines.append("| --- | --- | --- | --- |")

        for recommendation in recommendations:
            lines.append(_format_recommendation_row(recommendation))
    else:
        lines.append("No recommendations found. This repository looks strong.")

    lines.append("")
    lines.append("## Next Steps")
    lines.append("")

    missing_checks = [check for check in scan_report.checks if not check.passed]

    if missing_checks:
        for index, check in enumerate(missing_checks[:3], start=1):
            lines.append(f"{index}. {check.suggestion}")
    else:
        lines.append("No missing checks found. Keep the repository updated as the project grows.")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Generated by [RepoBoost](https://github.com/mohammad-azimi/RepoBoost).")
    lines.append("")

    return "\n".join(lines)


def _format_check_row(check: CheckResult) -> str:
    status = "✅ PASS" if check.passed else "❌ MISS"

    return (
        f"| {status} "
        f"| {_escape_markdown_table_cell(check.name)} "
        f"| {check.score}/{check.max_score} "
        f"| {_escape_markdown_table_cell(check.message)} "
        f"| {_escape_markdown_table_cell(check.suggestion)} |"
    )


def _format_recommendation_row(recommendation: Recommendation) -> str:
    return (
        f"| {_escape_markdown_table_cell(recommendation.priority)} "
        f"| {_escape_markdown_table_cell(recommendation.category)} "
        f"| {_escape_markdown_table_cell(recommendation.title)} "
        f"| {_escape_markdown_table_cell(recommendation.action)} |"
    )


def _escape_markdown_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()